services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
  halo:
    image: registry.fit2cloud.com/halo/halo:2.22
    container_name: halo
    restart: unless-stopped
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      halo_network:
    volumes:
      - ./halo/halo2:/root/.halo2
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      - TZ=Asia/Shanghai
      - JVM_OPTS=-Xmx1024m -Xms256m
    command:
      - --spring.r2dbc.url=r2dbc:pool:postgresql://halodb/halo
      - --spring.r2dbc.username=halo
      - --spring.r2dbc.password=Lzf07123.
      - --spring.sql.init.platform=postgresql
      - --halo.external-url=http://localhost:8090/
  halodb:
    image: postgres:15.4
    container_name: halodb
    restart: unless-stopped
    networks:
      halo_network:
    volumes:
      - ./halo/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=Lzf07123.
      - POSTGRES_USER=halo
      - POSTGRES_DB=halo
      - PGUSER=halo
  meilisearch:
    image: getmeili/meilisearch:v1.15
    container_name: meilisearch
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=<ZHj-gH1Sp_wRddqgWuvyM58-Hl8q3tv3ho7ViJhdPvA>
    volumes:
      - ./meilisearch:/meili_data
    ports:
      - 7700:7700
  frps:
    image: snowdreamtech/frps:debian
    container_name: frps
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./frp/frps.toml:/etc/frp/frps.toml
    network_mode: host
networks:
  halo_network:
